apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVMRENDQXBTZ0F3SUJBZ0lRSElteVRmUGpRcUdhYmdkVTVUVWFnakFOQmdrcWhraUc5dzBCQVFzRkFEQXYKTVMwd0t3WURWUVFERXlSaFl6RTVaR0l6WkMwMk5EZ3dMVFJsTlRndE9XSmxOQzFpTkRjMk1qWXpOR05oTm1NdwpJQmNOTWpVeE1qQTFNVFkxTURRMFdoZ1BNakExTlRFeE1qZ3hOelV3TkRSYU1DOHhMVEFyQmdOVkJBTVRKR0ZqCk1UbGtZak5rTFRZME9EQXROR1UxT0MwNVltVTBMV0kwTnpZeU5qTTBZMkUyWXpDQ0FhSXdEUVlKS29aSWh2Y04KQVFFQkJRQURnZ0dQQURDQ0FZb0NnZ0dCQU5ESE1sQUM2QjBqaWNCSVBzbTVvclF1YnZVR1RsWGU4UUhKek1MdQp1eStoSUhNUjdXUDJhTDg3a0ZWUTNzZ1lUczYzWEFCamFnWjdYTEozTVdnR2RwZXRvM3p1bXJHRmxrbGpPVUQ4CktwcEw1bjduNEREZzR3aXpwNEZlNUF3VEtySEtzaHpSQ1NXeEF6LzBBQytMSVoyUWlEZEtOcXVkdWVSdW5jTEMKa2FDeFRyRFh0cFI1akx2M2l1RHBYdlpJRHBhaW5nNVBvK3RnYUhKR2pncVhKMEpFNGdpMUVYOEZDVlNvTVNubwp2TUVidG1GWXN0K1lueFBKQlZWU1Bka1pacS9mYzBEQWJCTXJ1clQzUzYzYytjREFvNmhvREVYR1JWbnZYS3FwClo1a0pMU0htSUtkeGdiaGtLUWlINExXWCt1eVQ1MEpDUThCdWhPZVlTU240cDNhRnpybmQrV0dHa0hPRDBSeGgKcW5XdEZJOHA0VkJHTm0rYjkrQkZGQlpncWxiL0FTQVl3V2RqdEJMb29ZQkthMnNhaFlDOXBxNVl6MkVDZUwxTwpqRWZzT1NuY2tSUHBjRVFHVkFpdldEVnpENDJLYy84WENLQUNSUGVYUkZZWEhDTnFjVTNhTmRtUkkwWFcwdXQ4CnlCNFJSaHpibytDcWRQVFBnU0tDamhkeEJ3SURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQWdRd0R3WUQKVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVlMmRlcHVOSmhGajhYcDZaaDFPUlIyZzBOczh3RFFZSgpLb1pJaHZjTkFRRUxCUUFEZ2dHQkFFaWlHR2kxZDVRKytNY0UrWmJaQ0RQSmRTdGg1OGcxMk1aY2JwdExEVWdwCjlUUk5YUnJZR2lvN2lteGVMRkVQUDZvWW4wMlBsdXFLaFNBZmxJWlVlY1J1YkxNNnVwdVJOSzhxR21BaEIrc3gKS1BwMzRQRFNvUDF4aGdveFRIVUJoaW1uK2hDNWo2M3RINjFOTGIyaTYzNVhEbWtGOGNlUnppOW1mY3hrd1l5bQpMWHBqeE9kdjVmZ3R4YnBQL2Y3bDQwNkdiUnI1bDVDZXdpRW9JU1BhMGh4VEdYK2hLOG80M1MxV0FXM2NqV1ZSCkNFQytFNkZrVVlvb3YzKzB0VnRzemtrRFBoT3VxWkFRUUNWNEF4WlA3b01DVlUwSEtHYmd3ZUFkYmE3SnRsNGQKUWNNUmxxVmNxNDFJSWk4UC90TjNlaHVLZ3NBTjZVckx0Q2ZWMW5BaXgyenRRTFhsMGtyQVN0UEFoTHN3ZmhYRQpqVHJwZUxrbTJNOEJad3B0T0tjQW1aZ3RXWHdKcXNFK0pKU3VnSm5SQ2habUpBcGtJbGRmYzhZV3BZeEQ1Y2pSCkV5b2ZDMFZkdkpsK2swdHhCeGZkL3NSVkxoak5CTE9xR2xPa1c5YWp4T0R2d0pOZjRPS3pkNUdMTCtjd0x6UEgKZWRpQ1h2bWx3U2lpSHp0OWs5cThEdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://34.16.114.99
  name: harv-cluster-dev
contexts:
- context:
    cluster: harv-cluster-dev
    user: harv-cluster-dev
  name: harv-cluster-dev
current-context: harv-cluster-dev
kind: Config
preferences: {}
users:
- name: harv-cluster-dev
  user:
    auth-provider:
      config:
        cmd-args: config config-helper --format=json
        cmd-path: gcloud
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp

